### PR TITLE
Incorrect sort order

### PR DESCRIPTION
**Pull request by scottcwilson**
$products_options_query used pa.products_options_sort_order instead of
pov.products_options_values_sort_order

### CODE REVIEW

**Comment by mc12345678** [comment]
This section follows the same formatting/sequence as includes/modules/YOUR_TEMPLATE/attributes.php

See lines 41-97 of the file in this repo, specifically 67-71 and 97 as relates to this PR below.  Is this from an observation of an issue and backtracking to this area of the code or just a code review and observation?

``` php
41               if (PRODUCTS_OPTIONS_SORT_ORDER=='0') { 
42                 $options_order_by= ' order by LPAD(popt.products_options_sort_order,11,"0"), popt.products_options_name'; 
43               } else { 
44                 $options_order_by= ' order by popt.products_options_name'; 
45               } 
46  
47               //get the option/attribute list 
48               $sql = "select distinct popt.products_options_id, popt.products_options_name, popt.products_options_sort_order, 
49                               popt.products_options_type, popt.products_options_length, popt.products_options_comment, 
50                               popt.products_options_size, 
51                               popt.products_options_images_per_row, 
52                               popt.products_options_images_style, 
53                               popt.products_options_rows 
54               from        " . TABLE_PRODUCTS_OPTIONS . " popt 
55               left join " . TABLE_PRODUCTS_ATTRIBUTES . " patrib ON (patrib.options_id = popt.products_options_id) 
56               where patrib.products_id= :products_id: 
57               and popt.language_id = :languages_id: " . 
58               $options_order_by; 
59  
60               $sql = $db->bindVars($sql, ':products_id:', $_GET['products_id'], 'integer'); 
61               $sql = $db->bindVars($sql, ':languages_id:', $_SESSION['languages_id'], 'integer'); 
62               $products_options_names = $db->Execute($sql); 
63  
64               // iii 030813 added: initialize $number_of_uploads 
65               $number_of_uploads = 0; 
66  
67               if ( PRODUCTS_OPTIONS_SORT_BY_PRICE =='1' ) { 
68                 $order_by= ' order by LPAD(pa.products_options_sort_order,11,"0"), pov.products_options_values_name'; 
69               } else { 
70                 $order_by= ' order by LPAD(pa.products_options_sort_order,11,"0"), pa.options_values_price'; 
71               } 
72  
73               $discount_type = zen_get_products_sale_discount_type((int)$_GET['products_id']); 
74               $discount_amount = zen_get_discount_calc((int)$_GET['products_id']); 
75  
76               $zv_display_select_option = 0; 
77               //loop for each option/attribute listed 
78               while (!$products_options_names->EOF) { 
79                 $products_options_array = array(); 
80  
81                 /* 
82                 pov.products_options_values_id, pov.products_options_values_name, 
83                 pa.options_values_price, pa.price_prefix, 
84                 pa.products_options_sort_order, pa.product_attribute_is_free, pa.products_attributes_weight, pa.products_attributes_weight_prefix, 
85                 pa.attributes_default, pa.attributes_discounted, pa.attributes_image 
86              p.products_quantity 
87                 */ 
88  
89                 $sql = "select    pov.products_options_values_id, 
90                         pov.products_options_values_name, 
91                         pa.* 
92               from      " . TABLE_PRODUCTS_ATTRIBUTES . " pa, " . TABLE_PRODUCTS_OPTIONS_VALUES . " pov 
93               where     pa.products_id = '" . (int)$_GET['products_id'] . "' 
94               and       pa.options_id = '" . (int)$products_options_names->fields['products_options_id'] . "' 
95               and       pa.options_values_id = pov.products_options_values_id 
96               and       pov.language_id = '" . (int)$_SESSION['languages_id'] . "' " . 
97                 $order_by; 

```

**Comment by scottcwilson** [comment]
Debugging an issue.  Set sort orders on option values for an option and try it - you'll see they are not respected.

**Comment by mc12345678** [comment]
Well, I know I had to do a little "magic" to keep sort orders in line for the javascript because when using/tagging items by options_values_id (a number) current browsers do not respect the order in which the items are listed, but instead sort by that number.  So at one point/for one of the items I had to modify the sequencing (discussed in one of the issues back on the SBA 1.5.4 repo) and the method used was to preface the number with an underscore.  That doesn't mean that it works for all browsers and it certainly is not the best solution.  A better solution is to use a separate variable that tracks the expected sequence and then all things use that variable.

The other thing I noticed and I thought tried to fix in the DD code was that upon initial landing on an attribute page, attributes would be correctly sequenced, but if the page were refreshed then option names would be incorrectly sequenced and that there was some "default" sort order that was "expected" to exist or be respected. 

So some things are javascript/browser driven, some are ZC...

**Comment by scottcwilson** [comment]
In the current logic, the wrong sort field is being used.  It may be that additional JS logic is required for some browsers, but the underlying code is still wrong.  My PR fixes this.

**Comment by mc12345678** [comment]
But then an entry of a sort order made on the attributes controller would not have an effect on the outcome and the sort order would be only controlled by the "original" option_values.php entered value(s)?!  

Are you sure that the site doesn't need to 'Update All Products' Attribute Sort Orders
to match Option Value Default Sort Orders' option applied from within tools->Store Manager?  

Another way to look at it, when reviewing the table products_attributes for a single combination of products_id and options_id note the various values in the options_values_id field then match the same field to the products_options_values table. Do/don't they have the same sort order applied? (products_options_sort_order in products_attributes table, but products_options_values_sort_order in products_options_values table).

Just looking at the code, it appears that this plugin pulls the sort order from the products_attributes table and sorts first on those, then if two option values have the same sort order then the "characteristic" of interest (name or price) will be used.  On my test ZC 1.5.5 store I see these things swap as expected based on entries.

OV1: sort order 4, price 30
OV2: sort order 5, price 20
Either option value sort order presents these in OV1, OV2 order.
OV3: sort order 4, price 50
OV4: sort order 4, price 40
If option values are by name, then displayed as OV3, OV4, if option values are by price then OV4, OV3.
This was at least tried with multiple attributes with variations made to both the first and subsequent option names.  So, I am not seeing the problem that is described above...

**Comment by scottcwilson** [comment]
If your reasoning was correct, there wouldn't be a  products_options_values_sort_order in the options values table.  But there is!  Because some people want to specify a particular sort order for option values, which is neither name nor price.   I'm telling you, I had this issue (sort order from OV not being respected), made the change, and voila, the option values were sorted in the way the customer intended, as expressed in the options values table.

**Comment by mc12345678** [comment]
Not doubting that there was an issue of not respecting the sort order of option values as I've seen that happen with a standard ZC install (upgraded database at some point), but and maybe I didn't clarify, I tested this on a site that has SBA installed as provided from github to be able to provide the above results. I then also reviewed the github ZC code, searching for any use of products_options_values_sort_order which is only in the admin specifically when storing the data from the attributes controller. The sort order data from the attributes controller  allows resequencing from what is provided by the option values manager.

By coding to the products_options_values table, sort order changes made in the attributes controller will not be respected (in a default ZC install). The attributes controller does not update the independent products_options_values table. 

When generating the attributes for a product via the attributes controller, the option names are presented/shown as identified by the option names manager and the setting in configuration->product info for option names, the sort order for the applicable option values is assigned initially the value provided in the products_options_values table as the products_options_sort_order in the products_attributes table. Then upon modification in the attributes controller, the sort order is updated. 

But, sometimes there is a problem with the database and the data has to be reset/repaired...  It is this that appears to be the case for that site.

**Comment by mc12345678** [comment]
This ZC thread for example relates to what is described as happening: https://www.zen-cart.com/showthread.php?87470-Attribute-Sort-Order-not-responding

**Comment by catsma97504** [comment]
I am currently using v1.5.4 and am irritated at the lack of ability to sort options as needed.  I agree with the feedback that sorting needs to first use that in the products_options_values_sort_order column.  If you feel additional sorting is required, then simply add a secondary value, ie alpha or price or anything else that is a good catchall.

I know how I need the attributes to be sorted in the list when displayed.  And that should be followed.  It doesn't matter if I manually add sorting to the options when tied to a specific product.

For example, I have a size option that displays as follows:
- 6 ounce
- 3 ounce
- 12 ounce
- 1 kilogram
- 2 kilogram

This is neither alpha nor price sorted as the 3 ounce size has a smaller price point than the 6 ounce

FYI - Sorting attributes worked fine in 1.5.3 and earlier versions.  This bug was introduced in the current version.

**Comment by mc12345678** [comment]
Again, sorting issues were not introduced with this software at least in regards to using dynamic dropdowns and there was not a change in the code between what was used for ZC 1.5.3 and ZC 1.5.4, in fact, the code provided for ZC 1.5.3 is the same as that for ZC 1.5.4 and if the discussion of versions is related to Sba versions, the code is the same as well. The difference(s) that might exist in SBA code is that the javascript code applicable to ZC 1.5.4 is allowed to override the javascript provided in this plugin (rightfully so. 

Further, again if the above suggested query change which only affects the use of dynamic dropdowns which has only been setup to be used for product that have multiple attributes (option names) works, then the problem is not in the SBA code but in the database as effected by ZC on the products_attributes table. 

Now if dynamic dropdowns is not being used because the product has a single attribute and the SBA generated option name type SBA Basic dropdown (or similarly named) is being used with incorrect sort order but sort order is respected when using a standard dropdown then the issue is related to how the value for each option value is applied within the list which hasn't changed in any of the SBA versions from the time potteryhouse/jeking developed that. To confirm the issue though view the source of the page where the sort order is not correct. If the option values are listed by value= order, then report that as a change would need to be made to apply those values as text rather than numbers in order to respect sort order when using javascript. Also change the option name type from the SBA created option name to a standard dropdown option name and verify that sort order is restored. Report the results.

Again though, the above suggested change in sort order operation is not in accordance with ZC operation and indicates a problem with the products_attributes table/handling of it. It is not a problem of the code provided by SBA.

**Pull request closed without merging**
